routes/web.php
<?php



use Illuminate\Support\Facades\Route;



/*

|--------------------------------------------------------------------------

| Web Routes

|--------------------------------------------------------------------------

|

| Here is where you can register web routes for your application. These

| routes are loaded by the RouteServiceProvider within a group which

| contains the "web" middleware group. Now create something great!

|

*/



Route::get('/', function () {

     return redirect('admin');

});





//Auth::routes();

Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');

Route::get('/user-login', 'Auth\LoginController@showLoginForm')->name('login');

Route::post('/user-login', 'Auth\LoginController@Login')->name('login');

Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/{user}/email-verification', 'HomeController@emailVerification')->name('user.email.verification');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/delete/{id}', 'TimesController@DeleteTime');

Route::get('/check/courts/{id}', 'CourtsController@CheckTime');

Route::get('/check/products/{id}', 'BookingsController@CheckProduct');

Route::post('/check/sport', 'CourtsController@CheckSport');

Route::post('/check/book', 'BookingsController@store');

Route::post('/add/pay', 'BookingsController@AddPay');

Route::get('/export/invoice/{id}', 'BookingsController@ExportInvoice');

Route::get('/export/receipt/{id}', 'BookingsController@ExportReceipt');

Route::get('/order/product/{id}', 'BookingsController@DeleteOrderProduct');

Route::get('/backup','AdminController@backup');

Route::get('/active','BookingsController@active');


Route::name('client.')->prefix('client/')->middleware(['user'])->group(function(){

    Route::get('/bookings', 'HomeController@bookings')->name('bookings');
    
    Route::get('/all-bookings', 'HomeController@all_bookings')->name('allbookings');
    
    Route::get('/booking-detail/{id}', 'HomeController@bookings_detail')->name('bookingdetail');
    
    Route::post('check/courts', 'HomeController@checkSport')->name('check.courts');
    
    Route::post('store/bookings', 'HomeController@addBooking')->name('bookings.store');
    
    Route::post('check/tokens', 'HomeController@token_test')->name('bookings.token');
    
    Route::post('/booking', 'HomeController@resetForm')->name('reset.form');
    
    Route::get('/{court}/products/','HomeController@products')->name('bookings.products');
    
    Route::get('/manage-card', 'ProfileManageController@card_manage')->name('managecard');

    Route::get('/all-academy-inquires', 'HomeController@all_academy_inquires')->name('allacademyinquires');

    Route::get('/payment-cards', 'HomeController@allCards')->name('payment-cards');

    Route::post('/payment-cards', 'HomeController@cardDelete')->name('payment-card-delete');

});

Route::post('/client/response/bookings', 'HomeController@merchant_response');

Route::post('/client/response', 'HomeController@update_token')->name('post-token');

Route::get('/client/response/merchantDetails', 'HomeController@getMerchantDetails')->name('getMerchantDetails');

Route::get('/client/response/getMerchantToken', 'HomeController@getMerchantToken')->name('getMerchantToken');

// wallet process
Route::post('/client/process/processWallet', 'HomeController@processWallet')->name('processWallet');

Route::post('/client/process/processWalletSuccess', 'HomeController@processWalletSuccess')->name('processWalletSuccess');

Route::get('/client/booking/{booking_id}/thankyou/{booking_amount}', 'HomeController@thankyou')->name('wallet.booking.thankyou');


// Route::post('/client/response/bookings',function(){
//   return response()->json();
// });


// Route::get('/active', function () {

//     $update=  DB::table('users')->where('id', $_GET['id'])->where('email', $_GET['email'])->where('activation_code', $_GET['code'])->update(['status' => 1]);

//     if($update){

//         //Mail::to($_GET['email'])->send(new \App\Mail\Welcom());        

//         return "your Account is Active Now";

//     }else{

//      return "Error Active You Account";

//     }

// });



Route::group(['prefix' => 'admin'], function () {

    Voyager::routes();

    Route::get('/reports/booking', 'ReportsController@Booking');

    Route::get('/reports/schedule', 'ReportsController@Schedule');

    Route::get('/reports/finance', 'ReportsController@Finance');

    Route::get('/reports/academy', 'ReportsController@Academy');





});


Route::get('/academy', 'HomeController@loadview')->name('academy');
Route::post('/academy/availableClasses', 'HomeController@availableClasses')->name('availableClasses');
Route::post('/academy/submitAcademy', 'HomeController@submitAcademy')->name('submitAcademy');

Route::get('/getCategory', 'HomeController@getCategory')->name('getCategory');


Route::post('/getPrice', 'HomeController@getPrice')->name('getPrice');


// Without api
Route::post('/user/show', 'HomeController@UserDetails')->name('user.show');
Route::get('/academy/terms/', 'HomeController@Terms')->name('academy.terms');
Route::post('/academy/packages/check', 'HomeController@MyPackages')->name('academy.packages.check');

// Calculate Package
Route::post('/academy/calculate/amount', 'HomeController@CalculateAmount')->name('academy.calculate.amount');

// Subscription add  
Route::post('/academy/subscriptions/add', 'HomeController@StoreSubscriptions')->name('academy.subscriptions.add');

resources/views/pages/all-academy-inquires.blade.php
@extends('layouts.user')
@section('content')

<section class="aboutpage-section --sports-section">
    <div class="container-wrapper">

        <div class="mb-40">
            <h2 class="maintitle"> Academy Inquires</h2>

            <p class="maindesc --big">
                Please review your selection and confirm by clicking on the button to proceed to payment
            </p>
        </div>

        <div class="row">
            <div class="col-lg-3">
                @include('includes.sidebar-navigation')
            </div>

            <div class="col-lg-9">
                <div class="article right-side">

                    <div class="table-responsive">

                        <table class="table --schedule-table --review-table athletics text-left" id="all-bookings" width="100%" cellspacing="0">
                            <tr>
                                <th>Inquires #</th>
                                <th>Start Date</th>
                                <th>Age Category</th>
                                <th>Package Name</th>
                                <th>Class</th>
                                <th>Days</th> 
                                <th>Fees</th>
                            </tr>

                           @foreach($inquires_details as $key=> $detail)

                            <tr>
                                <td>
                                    {{$detail->id}}<br>
                                </td>
                                
                                <td>
                                    {{ date('d-m-Y',  strtotime($detail->start_date))}}
                                </td>

                                <td>
                                    {{$detail->age_title}}
                                </td>
                                <td>
                                   {{$detail->package_name}}
                                </td>
                                <td>
                                    {{$detail->class_title}}
                                </td>
                                <td> @php $s = str_replace( array( '[','"', ',', ']', '\''), ' ', $detail->num_days); @endphp
                                      {{ $s }}
                                </td>
                                <td>
                                    AED {{ number_format((float)$detail->subscription_fees, 2, '.', '') }}<br>
                                </td>
                            </tr>

                            @endforeach 
                        </table>

                    </div>

                </div>
            </div>
        </div>

    </div>
</section>
    

<!-- /.container-fluid -->
@endsection

resources/views/pages/all-cards.blade.php
@extends('layouts.user')
@section('content')

<section class="aboutpage-section --sports-section">
    <div class="container-wrapper">

        <div class="mb-40">
            <h2 class="maintitle">Account Details</h2>

        
        </div>

        <div class="row">
            <div class="col-lg-3">
                @include('includes.sidebar-navigation')
            </div>

            <div class="col-lg-9">
                <div class="article right-side">
                    
                   

                    <div class="table-responsive">

                        <table class="table --schedule-table --review-table athletics text-left" id="all-bookings" width="100%" cellspacing="0">
                            
                            <tr>
                                <th>Card Number</th>
                                <th>Action</th>
                            </tr>
                             @foreach($cards as $key=> $card)

                            <tr>
                                <td> {{$card->card_number}} </td>
                            
                                <td>
                    
 {{-- {!! Form::open(['method' => 'post', 'id' => 'deleteForm']) !!} --}}

                                 <form method="post" action="{{ route('client.payment-card-delete') }}">
                                     
                                     @csrf
                                     
                          <input type="hidden" name="token_name" value="{{$card->token_name}}" >
                          <input type="hidden" name="randomnum" value="{{$card->randomnum}}" >
                          <input type="hidden" name="booking_id" value="{{$card->booking_id}}" >
                          <input type="hidden" name="order_description" value="{{$card->order_description}}" >
                          <input type="hidden" name="amount" value="{{$card->amount}}" >
                             <input type="hidden" name="client_id" value="{{$card->user_id}}" >
                             
                             
                                            <button type="submit" class="deleteItem badge --danger mb-6">Remove</button>
                                 
                             
                    </form>


{{-- {!! Form::close() !!} --}}
    

 
                                </td>
                            </tr>

                            @endforeach
                        </table>

                    </div>

                </div>
            </div>
        </div>

    </div>
</section>

<!-- /.container-fluid -->


<script>
    
    
        //  var deleteResourceUrl = '{{ url()->current() }}';

        // $(document).ready(function() {
        //     $(document).on('click', '.deleteItem', function(e) {
        //         e.preventDefault();
        //         var deleteId = $(this).data('deleteId');
        //         $('#deleteForm').attr('action', deleteResourceUrl + '/' + deleteId);
        //         if (confirm('Are you sure?')) {
        //             $('#deleteForm').submit();
        //         }
        //     })
    
        // });
    
    
</script>


@endsection

resources/views/pages/allbookings.blade.php
@extends('layouts.user')
@section('content')

<section class="aboutpage-section --sports-section">
    <div class="container-wrapper">

        <div class="mb-40">
            <h2 class="maintitle">REVIEW BOOKING</h2>

            <p class="maindesc --big">
                Please review your selection and confirm by clicking on the button to proceed to payment
            </p>
        </div>

        <div class="row">
            <div class="col-lg-3">
                @include('includes.sidebar-navigation')
            </div>

            <div class="col-lg-9">
                <div class="article right-side">

                    <div class="table-responsive">

                        <table class="table --schedule-table --review-table athletics text-left" id="all-bookings" width="100%" cellspacing="0">
                            <tr>
                                <th>Booking #</th>
                                <th>Date/ Time</th>
                                <th>Pitch</th>
                                <th>Size</th>
                                <th>Price</th>
                                <th>Discount</th>
                                <th>Status</th>
                                <th>Total</th>
                                <th>Action</th>
                            </tr>

                            @foreach($booking_details as $key=> $detail)

                            <tr>
                                <td>
                                    {{$detail->id}}<br>
                                </td>
                                
                                <td>
                                    {{$detail->date}}<br>
                                    {{$detail->from}}<br>{{$detail->to}}
                                </td>

                                <td>
                                    {{$detail->pitch}}
                                </td>
                                <td>
                                   {{$detail->size}}
                                </td>
                                <td>
                                    {{$detail->price}}
                                </td>
                                <td>
                                    {{$detail->dicsount}}<br>
                                </td>
                                <td>
                                    
                                    @if($detail->status == 0)
                                        Unpaid         
                                    @else
                                        Paid        
                                    @endif
                                
                                </td>
                                <td>
                                    {{$detail->total}}<br>
                                </td>
                                <td>
                                    <a href="{{ url('client/booking-detail/'.$detail->id) }}" class="badge --success d-block mb-6" target="_blank"> 
                                        View
                                    </a>
                                    <a href="{{ url('../export/invoice/'.$detail->id) }}" class="badge --info d-block mb-6" target="_blank">
                                        Invoice
                                    </a>
                                    <a href="{{ url('../export/receipt/'.$detail->id) }}" class="badge --warning d-block" target="_blank">
                                        Receipt
                                    </a>
                                </td>
                            </tr>

                            @endforeach
                        </table>

                    </div>

                </div>
            </div>
        </div>

    </div>
</section>
    

<!-- /.container-fluid -->
@endsection

resources/views/pages/bk-payfort_pay.blade.php
                          <input type="hidden" id="aa" value="{{$client_token = $token_name}}" >


                    <?php
                    
                    
                    //  print("<pre>".print_r(request()->all(),true)."</pre>");
                    
                    
                    // print_r("========================");                    
                    // print_r($client_token);
                    // print_r("========================");
                    //exit;
                    
                        $randomnum=rand();
                        
                        $returnurl= URL::current();
                        // echo $returnurl;
                        $returnurl2= URL::to('/');
                        
                        $shaString  = '';
                        
                        $arrData    = array(
                        'command'            =>'AUTHORIZATION',
                        'access_code'        =>'GktW1EwizGB7tZ51ocEG', 
                        'merchant_identifier'=>'LmIAIBAK',
                        'merchant_reference' =>$randomnum.$booking_id,
                        'amount'             =>$totalAmount*100,
                        'currency'           =>'AED',
                        'language'           =>'en',
                        'merchant_extra'     =>$client_id,
                        'merchant_extra2'    =>$booking_id,
                        'merchant_extra3'    =>$randomnum,
                        'customer_email'     =>'test@payfort.com',
                        'order_description'  =>$sports . ' - ' . $pitch,
                        'return_url'         =>$returnurl2.'/client/response/bookings',
                        );
                        
                        if($client_token != null){
                            
                            $arrData['token_name'] = $client_token;
                        }
                        
                        ksort($arrData);
                        foreach ($arrData as $key => $value) {
                            $shaString .= "$key=$value";
                        }
                        
                     
                        
                        $shaString = "83/cPmhQ/ub0O3i8z0Qp4j-[" . $shaString . "83/cPmhQ/ub0O3i8z0Qp4j-[";
                        
                        
                        $signature = hash("sha256", $shaString);
                        
                        //   print("<pre>".print_r($arrData,true)."</pre>");  
                          
                        //   print("<pre>".print_r($client_token,true)."</pre>");
                          
                        //   print("<pre>".print_r($signature,true)."</pre>");
                        //   exit;
                        // 
                        $requestParams = array(
                        'command'            =>'AUTHORIZATION',
                        'access_code'        =>'GktW1EwizGB7tZ51ocEG',
                        'merchant_identifier'=>'LmIAIBAK',
                        'merchant_reference' =>$randomnum.$booking_id,
                        'amount'             =>$totalAmount*100,
                        'currency'           =>'AED',
                        'language'           =>'en',
                        'merchant_extra'     =>$client_id,
                        'merchant_extra2'    =>$booking_id,
                        'merchant_extra3'    =>$randomnum,
                        'customer_email'     =>'test@payfort.com',
                        'signature'          =>$signature,
                        'order_description'  =>$sports . ' - ' . $pitch,
                        'return_url'         =>$returnurl2.'/client/response/bookings',
                        
                         // demo
                        //  'command'            =>'AUTHORIZATION',
                        // 'access_code'        =>'zx0IPmPy5jp1vAz8Kpg7',
                        // 'merchant_identifier'=>'CycHZxVj',
                        // 'merchant_reference' =>$randomnum.$booking_id,
                        // 'amount'             =>$totalAmount*100,
                        // 'currency'           =>'AED',
                        // 'language'           =>'en',
                        // 'merchant_extra'     =>$client_id,
                        // 'merchant_extra2'    =>$booking_id,
                        // 'customer_email'     =>'test@payfort.com',
                        // 'signature'          =>'7cad05f0212ed933c9a5d5dffa31661acf2c827a',
                        // 'order_description'  =>$sports . ' - ' . $pitch,
                        // 'return_url'         =>$returnurl2.'/client/response/bookings',
                        
                        
                        
                        );
                        
                        if($client_token != null){
                            
                            $requestParams['token_name'] = $client_token;
                        }

                        // $redirectUrl = 'https://checkout.payfort.com/FortAPI/paymentPage';
                        $redirectUrl = 'https://sbcheckout.payfort.com/FortAPI/paymentPage';

                        echo "<form action='$redirectUrl' method='post' name='frm' class='default-form'> \n";
                        
                        foreach ($requestParams as $a => $b) {
                          
                        echo "\t<input type='hidden' name='".htmlentities($a)."' id='".htmlentities($a)."' value='".htmlentities($b)."'>\n";
                        }
                          


                        echo "\t<button type='submit' class='btn --btn-primary'>Pay Now</button>\n";
                           
                        echo "\t</form>\n";
                        // print("<pre>".print_r($requestParams,true)."</pre>");
                        
                    ?>
                    
                    
                    
                    
                    

resources/views/pages/bk-review.blade.php
@extends('layouts.user')
@section('content')
<!-- Begin Page Content -->

<section class="aboutpage-section --sports-section">
    <div class="container-wrapper">

        <div class="mb-40">
            <h2 class="maintitle">REVIEW BOOKING</h2>

            <p class="maindesc --big">
                Please review your selection and confirm by clicking on the button to proceed to payment
            </p>
        </div>

        <div class="row">
            <div class="col-lg-3">
                @include('includes.sidebar-navigation')
            </div>

            <div class="col-lg-9">
                <div class="article right-side">

                    <table class="table --schedule-table --review-table athletics text-left" id="dataTable1" width="100%" cellspacing="0">
                        <thead>
                            <th>Id</th>
                            <th>Sport</th>
                            <th>Pitch</th>
                            <th style="width: 180px">Time</th>
                            <th>Products*Qty</th>
                            <th>Rate</th>
                            <th>Total</th>
                        </thead>

                        <tbody>
                           
                            @foreach($details as $key=> $detail)

                            <tr>
                                <td>
                                    {{$booking_id = $detail['booking_id']}}<br>
                                </td>
                                <td>
                                    {{$sports = $detail['sports']}}<br>
                                </td>
                                <td>
                                    {{$pitch = $detail['pitch']}}<br>
                                </td>
                                <td>
                                    From: {{$detail['from']}}<br>
                                    To: {{$detail['to']}}
                                </td>
                                <td>
                                    @if(count($detail['name']) !==0)
                                       @foreach($detail['name'] as $key=> $productName)
                                       {{$productName}}
                                       <br>
                                       @endforeach
                                    @endif
                                </td>
                                <td>
                                   
                                  Price: {{$detail['court_rate']}}<br>
                                  Product Price: {{$detail['product_total']}}<br>
                                   
                                </td>
                                <td>
                                   
                                  {{$totalAmount = $detail['total']}}<br>
                                  <input type="hidden" value="{{$client_id = $detail['client_id']}}" >
                                </td>
                            </tr>
                            
                            @endforeach
                           
                            
                        </tbody>
                    </table>
                      <div class='default-form'>
                    
                    <div class='control-group'>
                        
                        <select name='client_id' id='client_id' class='form-field' required> 
                    
                        <option selected="selected" disabled value=''>Select Card</option> 
                    
                        </select>
                    </div>
                    
                    

                        <div id="pagerender"></div>
                     

                </div>
            </div>
        </div>

    </div>
</section>

<script>
    
    
$(document).ready(function(){
    
    console.log('test');
    
     var values = '{{ auth()->user()->id }}';

    $.ajax({
        url: "{{ route('getMerchantDetails') }}",
        type: "get",
        data: { values:values } ,
        dataType:"json",
        success: function (response) {
            
                console.log(response.success);

          // You will get response from your PHP page (what you echo or print)
        //  
          
          if(response.success == 200){
              
                            var obj = response.data;
                            // console.log(obj);
                            obj.forEach(function(element) {

                                console.log(element);
                                $('#client_id').append('<option value="' + element.id + '">'+ element.card_number +'</option>');
                            });
                            $('#client_id').append('<option value="">Add new card</option>');
              
              
          }else{
               $('#client_id').append('<option value="">Add new card</option>');
          }
          
                
          
        },
        error: function(jqXHR, textStatus, errorThrown) {
          console.log(textStatus, errorThrown);
        }
    });
    
    
    
    $('#client_id').on('change',function(){
        
        
        
        var get_id = $(this).val(); 
        
        var token_dyn = $('#token_dyn').val();
    
    console.log(get_id);    
        
         $.ajax({
        url: "{{ route('getMerchantToken') }}",
        type: "get",
        data: { token_name:'{{ $token_name }}','client_id':{{ $client_id }},'booking_id':{{ $booking_id }},'sports':'{{ $sports }}','pitch':'{{ $pitch }}','totalAmount':{{ $totalAmount }},values:get_id } ,
        dataType:"json",
        success: function (response) {
            
            $('#pagerender').empty();
            
                console.log(response);
          
              $('#pagerender').html(response.html);
              
              
              
              console.log(response.data);
              
              $('#token_name').val(response.data);
              
         
          
                
          
        },
        error: function(jqXHR, textStatus, errorThrown) {
          console.log(textStatus, errorThrown);
        }
    });
        
    });
   
    
    
    
});
    
    
</script>


    
     
<!-- /.container-fluid -->
@endsection

resources/views/pages/confirm.blade.php
@extends('layouts.app')
@section('pageClass', 'athleticpg inner-page')
@section('title', 'login')
@section('content')
<!-- About laliga -->
<section class="aboutpage-section --sports-section">
    <div class="container-wrapper">
        <div class="row align-items-center">
            <!-- <div class="col-lg-2 order-lg-last">
                <picture class="logo-icon">
                    <img src="/assets-web/images/logos/isdathletics.svg" alt="">
                </picture>
            </div> -->
            <div class="col-lg-10">
                <h2 class="maintitle">
                    <span class="fc-football">ISD Email Verification Code</span>
                </h2>
            </div>
        </div>
        <hr class="divider">
        <div class="content-section mb-40">
            <div class="row">
                <section class="col-xl-5 offset-xl-4 col-lg-6 offset-lg-3">
                    <div class="box --registration-box">
                        <h4 class="fc-white mb-40">Enter Email Verification Code before Continuing</h4>
                        <form class="default-form --registration-form">

                            <div class="control-group{{ $errors->has('code') ? ' has-error' : '' }}">
                                {!! Form::text('code', null, ['class'=>'form-field','required' => 'required',
                                'placeholder'=>'Enter Email Verification Code','id'=>'code','autocomplete'=>'off']) !!}
                                @if ($errors->has('player_nam'))
                                <span class="form-error">
                                    <strong>{{ $errors->first('code') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="control-group">
                                <button type="button" id="click" class="btn --btn-primary">
                                    {{ __('Submit') }}
                                </button>
                            </div>
                            <p class="fc-football">Check your email for verification code to verify your email address
                            </p>
                        </form>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
    
    $('#click').click(function(){
    
    var id={{$user}};
    var code=$("#code").val();
    
    $.ajax({
    type: 'POST',
    url: 'https://bookings.isddubai.com/api/v1/users/register/confirm',
    data: {id:id,code:code},
    dataType: 'json',
    success: function (data) {
    console.log(data);
    var status = data.status;
    var errormsg = data.msg;
    if(status==200)
    {
    window.location.href = "{{ route('client.bookings')}}";
    }
    else if(status==500){
    alert(errormsg);
    }
    },
    error: function (data) {
    console.log(data);
    }
    });
    });
    });
    </script>
</section>
<!-- Event snippet for Submit lead form - Popup conversion page -->
@endsection

resources/views/pages/fail.blade.php
@extends('layouts.user')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800"> Payment Failed</h1>
        <!--<h3>Review your payment</h3>-->
    </div>
    
    <div class="row">
        <div class="col-lg-12">
          <img class="failure-img" style="width:400px; margin: 30px auto;" src="{{ asset('public/assets-web/images/failure.png')}}">
        </div>
    </div>
    </div>
<!-- /.container-fluid -->
@endsection